#!/usr/bin/env python3
"""
Promethean — Q&A Engine
Ask questions against the Ray Peat knowledge base.

Usage:
    python tools/ask.py "why does Peat recommend aspirin?"
    python tools/ask.py                          # Interactive mode
    python tools/ask.py --file "question here"   # Save answer to wiki/queries/
"""

import sys
import re
import argparse
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent))
from config import (
    get_client, load_wiki_index, load_relevant_wiki_context,
    list_wiki_articles, load_article, WIKI_DIR, MODEL, MAX_TOKENS,
    SYSTEM_PROMPT, timestamp
)

try:
    from rich.console import Console
    from rich.markdown import Markdown
    console = Console()
    HAS_RICH = True
except ImportError:
    HAS_RICH = False


def print_response(text):
    """Print response with rich markdown if available."""
    if HAS_RICH:
        console.print(Markdown(text))
    else:
        print(text)


def build_context(question):
    """Build context from wiki for the question."""
    index = load_wiki_index()
    wiki_context = load_relevant_wiki_context(question, max_articles=8)

    context = f"""You have access to the Promethean knowledge base (a Ray Peat wiki).

{wiki_context}

Use this knowledge base to ground your answers. If the wiki doesn't cover something,
use your knowledge of Ray Peat's published work, but note when you're going beyond
what's in the wiki."""

    return context


def ask_single(client, question, conversation_history=None):
    """Ask a single question, return the answer."""
    context = build_context(question)

    messages = []
    if conversation_history:
        messages.extend(conversation_history)

    messages.append({
        "role": "user",
        "content": f"""Knowledge base context:
{context}

Question: {question}"""
    })

    response = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        system=SYSTEM_PROMPT,
        messages=messages,
    )

    return response.content[0].text


def file_answer(question, answer):
    """Save a Q&A pair as a wiki article in queries/."""
    queries_dir = WIKI_DIR / "queries"
    queries_dir.mkdir(parents=True, exist_ok=True)

    # Generate filename from question
    slug = re.sub(r'[^a-z0-9]+', '-', question.lower().strip("?. "))[:60].strip('-')
    date = datetime.now().strftime("%Y%m%d")
    filename = f"{date}-{slug}.md"

    content = f"""---
title: "{question}"
type: query
date: {timestamp()[:10]}
tags:
  - query
---

# {question}

> [!summary]
> Filed query from Promethean Q&A session.

{answer}

---
*Generated by Promethean ask.py on {timestamp()[:10]}*
"""

    filepath = queries_dir / filename
    filepath.write_text(content)
    print(f"\nFiled to: wiki/queries/{filename}")

    # Update index to mention new query
    index_path = WIKI_DIR / "_index.md"
    if index_path.exists():
        index = index_path.read_text()
        if "## Queries" in index:
            entry = f"\n- [[{slug}]] — {question}"
            index = index.replace("## Queries", f"## Queries{entry}", 1)
            index_path.write_text(index)

    return filepath


def interactive_mode(client):
    """Interactive Q&A session with conversation memory."""
    print("=" * 60)
    print("  PROMETHEAN — Ray Peat Knowledge Base Q&A")
    print("=" * 60)
    print("\nAsk anything about Ray Peat's framework.")
    print("Commands: 'quit' to exit, 'file' to save last answer, 'clear' to reset\n")

    conversation = []
    last_question = None
    last_answer = None

    while True:
        try:
            question = input("\n> ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nGoodbye.")
            break

        if not question:
            continue

        if question.lower() in ("quit", "exit", "q"):
            print("Goodbye.")
            break

        if question.lower() == "clear":
            conversation = []
            print("Conversation cleared.")
            continue

        if question.lower() == "file":
            if last_question and last_answer:
                file_answer(last_question, last_answer)
            else:
                print("No previous answer to file.")
            continue

        print()
        answer = ask_single(client, question, conversation)
        print_response(answer)

        # Track conversation
        conversation.append({"role": "user", "content": question})
        conversation.append({"role": "assistant", "content": answer})
        last_question = question
        last_answer = answer

        # Keep conversation manageable
        if len(conversation) > 20:
            conversation = conversation[-10:]


def main():
    parser = argparse.ArgumentParser(description="Promethean Q&A Engine")
    parser.add_argument("question", nargs="?", help="Question to ask")
    parser.add_argument("--file", action="store_true",
                        help="Save the answer to wiki/queries/")
    args = parser.parse_args()

    client = get_client()

    if args.question:
        answer = ask_single(client, args.question)
        print_response(answer)
        if args.file:
            file_answer(args.question, answer)
    else:
        interactive_mode(client)


if __name__ == "__main__":
    main()
